spring:
  application:
    name: websocket
  profiles:
    active: mysql-dev
server:
  port:
    8888
  ssl:
    enabled: true
    key-store: classpath:hirex.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: hirex

logging:
  level:
    root: INFO
    com:
      ptit:
        websocket:
          controller: DEBUG
  