spring:
  application:
    name: websocket
server:
  port: 8888
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: 123456
    key-store-type: JKS
    key-alias: hirex-ssl

logging:
  level:
    root: INFO
    com:
      ptit:
        websocket:
          controller: DEBUG
  