services:
  postgres:
    image: postgres:latest
    container_name: hirex-postgres-container
    environment:
      POSTGRES_USER: hirex
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: hirex
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
    networks:
      - backend

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: hirex
      MINIO_ROOT_PASSWORD: hirex
    command: server --console-address ":9001" /data

networks:
  backend:
    driver: bridge