services:
  main-service:
    build:
      context: .
      dockerfile: ./main/Dockerfile
    image: main:latest
    ports:
      - "8080:8080"
    restart: always

  websocket-service:
    build:
      context: .
      dockerfile: ./websocket/Dockerfile
    image: websocket:latest
    ports:
      - "8888:8888"
    restart: always
    depends_on:
      - main-service