services:
  postgres:
    image: postgres:latest
    container_name: hirex-postgres-container
    environment:
      POSTGRES_USER: hirex
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: hirex
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
