services:
  mongodb:
    image: mongo:latest
    container_name: hirex-mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: hirex
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: hirex
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
