server:
  port: 8080

spring:
  profiles:
    active: mysql-dev
  data:
    redis:
      port: 6379
      host: 172.25.0.2
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: hirex.ptit@gmail.com
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
  cache:
    type: redis
    redis:
      time-to-live: 1800000
      cache-null-values: false

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG

jwt:
  expiry-time-secs: 3600
  access-key: 

minio:
  access:
    key: 
  secret:
    key: 
  url:
    public: https://s3.deploy-hirexptit.io.vn
    private: https://s3.deploy-hirexptit.io.vn
  bucket: hirex

websocket-service:
  baseUrl: https://ws.deploy-hirexptit.io.vn

recommend-service:
  baseUrl: https://re.deploy-hirexptit.io.vn/api

frontend-service:
  baseUrl: https://deploy-hirexptit.io.vn
