server:
  port: 8080
spring:
  profiles:
    active: mysql-dev
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:36.50.134.219}
  mail:
    host: smtp.gmail.com
    port: 587
    username: s2kius2t@gmail.com
    password: mnylpqwpyuztxypm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: hirex.cskh@gmail.com

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
