server:
  port: 8080

spring:
  profiles:
    active: mysql-dev
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:10.242.156.132}
  mail:
    host: smtp.gmail.com
    port: 587
    username: s2kius2t@gmail.com
    password: mnylpqwpyuztxypm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: hirex.ptit@gmail.com
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
  cache:
    type: redis
    redis:
      time-to-live: 1800000
      cache-null-values: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG

jwt:
  expiry-time-secs: 3600
  access-key: c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=

minio:
  access:
    key: ${S3_ACCESS_KEY_ID:fIqgc4weD1UTFTWHL6QM}
  secret:
    key: ${S3_SECRET_ACCESS_KEY:JSFFZondksn3x6g8E9eVktFKed1TgaTd8cVntuue}
  url:
    public: ${S3_ENDPOINT:https://s3.deploy-hirexptit.io.vn}
    private: ${S3_ENDPOINT_PRIVATE:https://s3.deploy-hirexptit.io.vn}
  bucket: ${S3_BUCKET:hirex}

websocket-service:
  baseUrl: https://ws.deploy-hirexptit.io.vn

recommend-service:
  baseUrl: https://re.deploy-hirexptit.io.vn/api